<form action="../requests/add.php?tableName=<?=$tableName?>" method="POST" >
<?php foreach($getColumnNames as $key => $value): ?>
    <?php if($value == 'id') continue;?>
    <label for=<?=htmlspecialchars($value)?>><?=htmlspecialchars(ucfirst($value))?></label></br>
    <input type="text" name=<?=htmlspecialchars($value)?>></br>
<?php endforeach ?> 
</br><button type='submit'>Add</button>
</form>