
<?php $i = 0; ?>
<form action="../requests/edit.php?tableName=<?= $tableName ?>&id=<?= $_GET['id'] ?>" method="POST" >

<?php foreach(($getColumnNames) as $key => $value): ?>
    <?php if($value == 'id') continue; $i++?>

    <label for=<?=htmlspecialchars($value)?>><?=htmlspecialchars(ucfirst($value))?></label></br>
    <input type="text" name=<?=htmlspecialchars($value)?> value="<?= $placeholderData[$i] ?>"></br>
<?php endforeach ?> 

</br><button type='submit'>Edit</button>
</form>
