
<h2>Edit Card</h2>
<form action="../requests/edit.php?table=<?= $table ?>&id=<?= $id ?>" method="POST" >

<?php foreach(($data) as $key => $value): ?>
    <?php if($key == 'id') continue;?>

    <label for=<?=htmlspecialchars($key)?>><?=htmlspecialchars(ucfirst($key))?></label></br>
    <input type="text" placeholder="<?= htmlspecialchars($key) ?>" name=<?=htmlspecialchars($key)?> value="<?= $data[$key] ?>"></br>
<?php endforeach ?> 

</br><button class="button" style="padding: 10px 20px" type='submit'>Edit</button>
</form>
