
<h1>Garage</h1>
<?= $banner->render() ?>
<h3>Cars</h3>
<a href="pages/addCard.php?tableName=<?=$GLOBALS['config']['mysql']['tableName']['cards_db']?>">Add New Car</a>
<div style="display: flex; gap: 10px; margin-top: 10px;"> 
  <?= $widgetCardCars->render(); ?>
</div>
<h3>Moto</h3>
<a href="pages/addCard.php?tableName=<?=$GLOBALS['config']['mysql']['tableName']['moto_db']?>">Add New Moto</a>
<div style="display: flex; gap: 10px; margin-top: 10px;"> 
  <?= $widgetCardMoto->render(); ?>
</div>
