<div style='display:flex; justify-content: space-between; align-items: center;'>
    <h3>login: <?= $login?></h3>
    <a href='pages/logout.php' style="
            display: inline-block;
            padding: 10px 20px;
            background-color: #eaeaea;
            color: #333;
            text-decoration: none;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-weight: bold;">Exit</a>
</div>

