<a href='/pages/registration.php' style="
            display: inline-block;
            padding: 10px 20px;
            background-color: #eaeaea;
            color: #333;
            text-decoration: none;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-weight: bold;">Register</a>
<a href='/pages/authorization.php' style="
            display: inline-block;
            padding: 10px 20px;
            background-color: #eaeaea;
            color: #333;
            text-decoration: none;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-weight: bold;">Authorization</a>