        <div style='padding:10px; border: #000 solid'>
        <?php
        
            foreach($data as $name => $item) {
                if($item == NULL || $name == 'id'){
                    continue;
                }
        ?>
                <p><?= htmlspecialchars(ucfirst($name)) ?>: <b><?= htmlspecialchars($item) ?></b></p>
        <?php
            }
        ?>
            <div style="height:30px; display:flex; justify-content: space-evenly; align-items: center; border-bottom: 1px solid #000; padding: 5px;">
                <div class="likes" style="cursor: pointer;">
                    <img src="svg/like.svg" alt="like" class="
                    <?php
                        if($like_active == 1) {
                            echo 'like_dislike_active';
                        }
                        else 
                        {
                            echo 'like_dislike';
                        }
                    ?>
                    " data-id="<?= $data['id'] ?>">
                </div>
                <span class="likes_counter"> 
                    <?= $likes ?>
                </span>
                <div class="dislikes" style="cursor: pointer;">
                    <img src="svg/dislike.svg" alt="dislike" class="
                    <?php
                        if($like_active == -1) {
                            echo 'like_dislike_active';
                        }
                        else 
                        {
                            echo 'like_dislike';
                        }
                    ?>
                    " data-id="<?= $data['id'] ?>">
                </div>
            </div>
            <div style='display: flex; justify-content: space-around; padding-top: 5px;'>
                <a href="pages/editCard.php?table=<?= $sub_table_name ?>&id=<?= $data['id'] ?>" class="button button_edit">Edit</a>
                <a href="requests/delete.php?table=<?= $sub_table_name ?>&id=<?= $data['id'] ?>" class="button button_delete">Delete</a>
            </div>
        </div>

