<?php 
    foreach ($data as $key => $value):
        if(gettype($value) == 'string') {
            continue;
        }

            ?>
            <div style='padding:10px; border: #000 solid'>
            <?php foreach($value as $name => $item):?>
                <?php if ($item == NULL) { ?>
                    <p style='color:grey; text-align:center;'><?= ucfirst($name) ?></p>
                <?php continue; }?>
                <?php if ($name != 'id'){ ?>
                    <p><?= ucfirst($name) ?>: <b><?= $item ?></b></p>
                <?php } ?>
            <?php endforeach?>
            </div>
        <?php endforeach?>